% RunConfidenceReportModel
% Runs the confidence report model on simulated agent
% data and plots the results.
%
% Produces a 2x3 figure with:
%   (1) Calibration curve        : P(correct) vs time investment
%   (2) Vevaiometric curve       : mean time investment vs |evidence|
%   (3) Conditioned psychometric : P(correct) vs |evidence|, split by confidence
%   (4) Psychometric curve       : P(choice left) vs evidence
%   (5) Mapping function m(c)    : estimated time investment vs confidence
%   (6) Alpha log-likelihood     : model fit quality and best-fit alpha
%
% Three model variants are overlaid on panels 1-3:
%   - Shuffle control  (alpha = 0, dashed): confidence fully randomized
%   - Optimal model    (alpha = 1, thin solid): confidence used perfectly
%   - Best-fit model   (alpha_best, thick solid): maximum likelihood alpha
%
% Prerequisites: MATLAB Optimization Toolbox (for fmincon in alpha fitting)
% Data:          generated by functions/MakeInvestmentAgent.m -> data/InvestmentAgentData.mat
%
% Ott et al. 2026
% torben.ott@bccn-berlin.de
%

%% --- Settings -----------------------------------------------------------
% quickplot = true  : fast run (~1 min), suitable for exploration.
%                     Uses fewer Monte Carlo samples, no bootstrap CIs.
% quickplot = false : full run (~hours), suitable for publication figures.
%                     Uses 10M samples and 999 bootstrap iterations.
quickplot = true;

%% --- Setup --------------------------------------------------------------
SCRIPTPATH = fileparts(mfilename('fullpath'));
DATAPATH   = fullfile(SCRIPTPATH, 'data');
DATAFILE   = 'InvestmentAgentData.mat';

addpath(fullfile(SCRIPTPATH, 'functions'));
rng(1);  % fix random seed for reproducibility

%% --- Load simulated agent data ------------------------------------------
tmp           = load(fullfile(DATAPATH, DATAFILE));
SimulatedMeta = tmp.Meta;
SimulatedData = tmp.Data;

%% --- Assemble data struct -----------------------------------------------
% Time investment is only observable on unrewarded trials (errors, omissions,
% (probe trials)).
Data = struct();

Data.DV      = SimulatedData.x(:);           % stimulus evidence
Data.ChoiceA = SimulatedData.d(:);           % binary choice (true = positive DV towards left)
Data.Outcome = SimulatedData.correct(:);     % accuracy (1 = correct, 0 = error)
Data.Omission= SimulatedData.omission(:);    % reward omission (probe trials)

Data.Conf    = SimulatedData.ti(:);          % time investment (behavioral confidence report)
Data.Conf(~SimulatedData.unrewarded) = NaN;  % mask rewarded trials (TI not fully observed)

%% --- Figure layout ------------------------------------------------------
H_Fig = figure('Position', [520, 140, 1103, 567], 'Color', [1, 1, 1]);
for k = 1:6
    H(k) = subplot(2, 3, k);
    hold on;
end

%% --- Psychometric model fit ---------------------------------------------
% Fits a cumulative Gaussian to P(choice A | DV) to recover perceptual
% sigma and bias. Bias is then zeroed; the confidence report model treats agent as unbiased.
Params = struct();
Params.H        = H(4);
Params.Function = 'erf-full';
Params.Bin      = 9;

Data = PsychometricModel(Data, Params);

BiasBackup    = Data.Fit.Bias;  % store in case needed later
Data.Fit.Bias = 0;              % center model at DV = 0

%% --- Model parameters ---------------------------------------------------
% quickplot trades accuracy for speed by reducing Monte Carlo samples,
% alpha grid resolution, and disabling bootstrap CIs on the alpha fit.
if quickplot
    ModelN    = 1000000;  % Monte Carlo trials for belief function estimation
    Nalpha    = 20;      % number of alpha values in grid search
    Nfitboot  = 1;       % bootstrap iterations (1 = no bootstrap)
else
    ModelN    = 10000000;
    Nalpha    = 100;
    Nfitboot  = 999;
end

% Shared model parameters
Params.Hmapping            = H(5);
Params.Halpha              = H(6);
Params.Subject             = 'Simulated Agent';
Params.Model.N             = ModelN;
Params.Model.nhist         = 100;       % bins for KS density estimation
Params.Model.Nalpha        = Nalpha;
Params.Model.Nfitboot      = Nfitboot;
Params.Model.GOFplot       = true;
Params.Model.GOFLabel      = true;
Params.Model.UniformDV     = false;     % use empirical DV distribution
Params.Model.efficacy_type = 'randreplace';

%% --- Model variant 1: shuffle control (alpha = 0) -----------------------
% Confidence is randomly permuted, breaking the DV-confidence link.
% This is the null model, no link between time investment and evidence.
Params.Model.Shuffle   = true;
Params.Model.fit_alpha = false;
Params.plotmapping     = false;
DataShuffle = ConfidenceReportModel(Data, Params);

%% --- Model variant 2: optimal model (alpha = 1) -------------------------
% Confidence is used perfectly to guide time investment (no time investment/metacognitive noise).
% Upper bound for the confidence signatures.
Params.Model.Shuffle   = false;
Params.Model.fit_alpha = false;
Params.Model.alpha     = 1;
Params.plotmapping     = false;
DataOptimal = ConfidenceReportModel(Data, Params);

%% --- Model variant 3: best-fit alpha (MLE) ------------------------------
% Fits alpha by maximizing the likelihood of the observed confidence
% distribution given the model. Alpha captures the degree to which the
% subject's time investment tracks their statistical confidence (efficacy).
% Plots the mapping function m(c) in panel 5 and the LL curve in panel 6.
Params.Model.Shuffle   = false;
Params.Model.fit_alpha = true;
Params.plotmapping     = true;
DataAlpha = ConfidenceReportModel(Data, Params);

%% --- Plot empirical confidence signatures -------------------------------
ParamsPlot             = struct();
ParamsPlot.NBinDV      = 9;
ParamsPlot.NBinConf    = 7;
ParamsPlot.AbsDV       = true;
ParamsPlot.ErrorBar    = 'sem';
ParamsPlot.Figure      = H_Fig;
ParamsPlot.Axes        = H(1:3);
ParamsPlot.MinPoints   = 5;
ParamsPlot.LineWidth   = 0;
ParamsPlot.ConfMed     = [];
[DataBack, ~] = PlotConfidenceSignatures(Data, ParamsPlot);

%% --- Plot model signatures: shuffle control --------------------
ParamsPlot             = struct();
ParamsPlot.NBinDV      = 20;
ParamsPlot.NBinConf    = 20;
ParamsPlot.AbsDV       = true;
ParamsPlot.ErrorBar    = false;
ParamsPlot.Figure      = H_Fig;
ParamsPlot.Axes        = H(1:3);
ParamsPlot.LineWidth   = 1;
ParamsPlot.LineStyle   = '--';
ParamsPlot.MinPoints   = 20;
ParamsPlot.ConfMed     = [];
[~, ~] = PlotConfidenceSignatures(DataShuffle.Model, ParamsPlot);

%% --- Plot model signatures: optimal model ------------------
ParamsPlot             = struct();
ParamsPlot.NBinDV      = 20;
ParamsPlot.NBinConf    = 20;
ParamsPlot.AbsDV       = true;
ParamsPlot.ErrorBar    = false;
ParamsPlot.Figure      = H_Fig;
ParamsPlot.Axes        = H(1:3);
ParamsPlot.LineWidth   = 1;
ParamsPlot.LineStyle   = '-';
ParamsPlot.MinPoints   = 20;
ParamsPlot.ConfMed     = [];
[~, ~] = PlotConfidenceSignatures(DataOptimal.Model, ParamsPlot);

%% --- Plot model signatures: best-fit alpha  ----------------
ParamsPlot             = struct();
ParamsPlot.NBinDV      = 20;
ParamsPlot.NBinConf    = 20;
ParamsPlot.AbsDV       = true;
ParamsPlot.ErrorBar    = false;
ParamsPlot.Figure      = H_Fig;
ParamsPlot.Axes        = H(1:3);
ParamsPlot.LineWidth   = 3;
ParamsPlot.LineStyle   = '-';
ParamsPlot.MinPoints   = 20;
ParamsPlot.ConfMed     = [];
[~, ~] = PlotConfidenceSignatures(DataAlpha.Model, ParamsPlot);

%% --- Figure annotations -------------------------------------------------
H(4).Title.String=['Psychometric curve (\sigma_{fit} = ',num2str(round(Data.Fit.Sigma*100)/100),')'];
set(gcf, 'Units', 'normalized');
str{1} = Params.Subject;
str{2} = ['\sigma_{true} = ', num2str(SimulatedMeta.sigma)];
str{3} = ['\alpha_{true} = ', num2str(SimulatedMeta.alpha)];
annotation('textbox', [0.01, 0.8, 0.07, 0.18], ...
    'String', str, ...
    'Interpreter', 'tex', ...
    'BackgroundColor', [1,1,1], ...
    'EdgeColor', 'none', ...
    'Units', 'normalized', ...
    'FontSize', 9);
RedoTicks(gcf);

%% --- Axis limits --------------------------------------------------------
% Auto-scale vevaiometric x-axes to data range, then apply fixed limits
datamax = max([DataBack.Axes.Vevaio.Correct.XData, DataBack.Axes.Vevaio.Error.XData]);
if ~isnan(datamax)
    H(2).XLim = [H(2).XLim(1), datamax + 0.1];
    H(3).XLim = H(2).XLim;
end

% Fixed limits for consistent presentation
H(1).YLim = [0.45, 1];
H(2).XLim = [0, 1];
H(3).XLim = [0, 1];   H(3).YLim = [0.5, 1];
H(4).YLim = [0, 1];   H(4).XLim = [-1, 1];

%% --- Axis ticks ---------------------------------------------------------
H(1).YTick = [0.5, 1];    H(1).YTickLabel = H(1).YTick;
H(2).XTick = [0, 0.5, 1];
H(3).XTick = [0, 0.5, 1];
H(3).YTick = [0.5, 1];    H(3).YTickLabel = H(3).YTick;
H(4).XTick = [-1, 0, 1];
H(4).YTick = [0, 0.5, 1];
H(5).XTick = [0.5, 1];

%% --- Legend -------------------------------------------------------------
axes(H(1));
l = legend({'Data', 'Shuffle (\alpha=0)', 'Optimal (\alpha=1)', 'Bounded (\alpha_{best})'});
l.Location = 'southeast';

%% --- save figure --------------------------------------------------------
print(H_Fig, fullfile(SCRIPTPATH,'output', 'output.png'), '-dpng', '-r150');
fprintf('Saved figure to %s\n', fullfile(SCRIPTPATH,'output', 'output.png'));